// Generated by IB v0.4.4 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <AppKit/AppKit.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>
#import <OpenGL/OpenGL.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
-(IBAction) applicationDidFinishLaunching:(id) notification;
-(IBAction) buildWindow;
-(IBAction) view;
-(IBAction) create_syphon_server;
-(IBAction) start_timer;
-(IBAction) image_to_pixel;
-(IBAction) publish;

@end

@interface MainMenu: NSWindowController

@property IBOutlet NSImageView * imageView;

-(IBAction) initWithFrame:(id) rect;

@end

